[workspace]
members = [
    "examples/rust_book/*", "examples/rust_by_example/hello_world",
    #"examples/rust-by-example/*",
    #"projects/*",
]

# Expliciilty pinning to use the new 2024 resolver
resolver = "3"
